import { Fragment } from "react"
import Head from "next/head"

export default function Onboarding() {
  return (
    <Fragment>
      <Head>
        <title>Interlace | Web3 Contributor Marketplace</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex items-center justify-center text-4xl min-h-screen">
        <p>Here will be unicorns. 🦄</p>
      </main>
    </Fragment>
  )
}
